import type { Metadata } from "next";
import { Agbalumo, Roboto } from "next/font/google";
import "../globals.scss";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "200", "300","400", "500", "600", "700", "800", "900"],
  variable: "--font-roboto",
  display: 'swap',
})
const agbalumo = Agbalumo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ag",
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${roboto.variable} ${agbalumo.variable}`}>
        {children}
      </body>
    </html>
  );
}
