import Header from "@/components/blocks/header/Header";
import "./globals.scss";
import "./__var.scss";
import type { Metadata } from "next";
import { Agbalumo, Roboto } from "next/font/google";
import Footer from "@/components/blocks/footer/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "200", "300","400", "500", "600", "700", "800", "900"],
  variable: "--font-roboto",
})
const agbalumo = Agbalumo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-agbalumo",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${roboto.variable} ${agbalumo.variable}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
